src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: AddressRepository::class)]
class Address
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\Column(type: 'string', length: 10, nullable: true)]
    private string $street_number;

    #[ORM\Column(type: 'string', length: 255)]
    private string $street;

    #[ORM\Column(type: 'string', length: 5)]
    private string $zipcode;

    #[ORM\Column(type: 'string', length: 50)]
    private string $city;

    #[ORM\Column(type: 'string', length: 50)]
    private string $country;

    #[ORM\Column(type: 'boolean')]
    private bool $isBilling;

    #[ORM\Column(type: 'boolean')]
    private bool $isDelivery;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'addresses')]
    #[ORM\JoinColumn(nullable: false)]
    private User $user;

    #[ORM\OneToMany(mappedBy: 'billing_address', targetEntity: Invoice::class)]
    private $invoices_billing_address;

    #[ORM\OneToMany(mappedBy: 'delivery_address', targetEntity: Invoice::class)]
    private $invoices_delivery_address;

    /**
     * @return ArrayCollection
     */
    public function getInvoicesBillingAddress(): ArrayCollection
    {
        return $this->invoices_billing_address;
    }

    /**
     * @param ArrayCollection $invoices_billing_address
     */
    public function setInvoicesBillingAddress(ArrayCollection $invoices_billing_address): void
    {
        $this->invoices_billing_address = $invoices_billing_address;
    }

    /**
     * @return ArrayCollection
     */
    public function getInvoicesDeliveryAddress(): ArrayCollection
    {
        return $this->invoices_delivery_address;
    }

    /**
     * @param ArrayCollection $invoices_delivery_address
     */
    public function setInvoicesDeliveryAddress(ArrayCollection $invoices_delivery_address): void
    {
        $this->invoices_delivery_address = $invoices_delivery_address;
    }

    public function __construct()
    {
        $this->invoices_billing_address = new ArrayCollection();
        $this->invoices_delivery_address = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStreetNumber(): ?string
    {
        return $this->street_number;
    }

    public function setStreetNumber(?string $street_number): self
    {
        $this->street_number = $street_number;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }


    public function __toString(){
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get the value of isBilling
     */
    public function getIsBilling()
    {
        return $this->isBilling;
    }

    /**
     * Set the value of isBilling
     */
    public function setIsBilling($isBilling): self
    {
        $this->isBilling = $isBilling;

        return $this;
    }

    /**
     * Get the value of isDelivery
     */
    public function getIsDelivery()
    {
        return $this->isDelivery;
    }

    /**
     * Set the value of isDelivery
     */
    public function setIsDelivery($isDelivery): self
    {
        $this->isDelivery = $isDelivery;

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices[] = $invoice;
            $invoice->setBillingAddress($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getBillingAddress() === $this) {
                $invoice->setBillingAddress(null);
            }
        }

        return $this;
    }
}

src/Entity/Invoice.php
<?php

namespace App\Entity;


use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: InvoiceRepository::class)]

class Invoice
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\Column(type: 'string', length: 15)]
    private string $payment_method;

    #[ORM\Column(type: 'date')]
    private \DateTime $order_date;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'invoices')]
    private User $user;

    #[ORM\OneToMany(mappedBy: 'invoice', targetEntity: ProductOrder::class, cascade: ["persist"], orphanRemoval: true)]
    #[ORM\JoinColumn(nullable: true)]
    private Collection|null $productOrders;

    #[ORM\ManyToOne(targetEntity: Address::class, inversedBy: 'invoices_billing_address')]
    #[ORM\JoinColumn(nullable: true)]
    private $billing_address;

    #[ORM\ManyToOne(targetEntity: Address::class, inversedBy: 'invoices_delivery_address')]
    #[ORM\JoinColumn(nullable: true)]
    private $delivery_address;


    public function __construct()
    {
        $this->date = new \DateTime();
        $this->productOrders=new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPaymentMethod(): ?string
    {
        return $this->payment_method;
    }

    public function setPaymentMethod(string $payment_method): self
    {
        $this->payment_method = $payment_method;

        return $this;
    }

    public function getOrderDate(): ?\DateTime
    {
        return $this->order_date;
    }

    public function setOrderDate(\DateTime $order_date): self
    {
        $this->order_date = $order_date;

        return $this;
    }

    /**
     * @param ?Collection|null $productOrders
     */
    public function setProductOrders(Collection|null $productOrders): void
    {
        $this->productOrders = $productOrders;
    }

    /**
     * @returnCollection|null
     */
    public function getProductOrders(): Collection|null
    {
        return $this->productOrders;
    }

    public function addProductOrder(ProductOrder $productOrder): self
    {
        if (!$this->productOrders->contains($productOrder)) {
            $this->productOrders[] = $productOrder;
            $productOrder->setInvoice($this);
        }
        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTotalHTPrice(){

        $totalHTPrice = 0;
        foreach ($this->getProductOrders() as $productOrder){
        $totalHTPrice += $productOrder->getHTPrice();
        }
        return $totalHTPrice;

    }

    public function getTotalTTCPrice(){

        $totalTTCPrice = 0;
        foreach ($this->getProductOrders() as $productOrder){
            $totalTTCPrice += $productOrder->getTTCPrice();
        }
        return $totalTTCPrice;

    }

    public function getBillingAddress(): ?Address
    {
        return $this->billing_address;
    }

    public function setBillingAddress(?Address $billing_address): self
    {
        $this->billing_address = $billing_address;

        return $this;
    }

    public function getDeliveryAddress(): ?Address
    {
        return $this->delivery_address;
    }

    public function setDeliveryAddress(?Address $delivery_address): self
    {
        $this->delivery_address = $delivery_address;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username', TextType::class, [
                'required'=>true,
                'label'=>"Nom d'utilisateur",
                'label_attr'=>['class'=>'text-bold my-2'],
                'attr'=>['class'=>'form-control mt-2']
            ])
            ->add('plainPassword', RepeatedType::class, [
                'type' => PasswordType::class,
                'label'=> 'Choix du mot de passe',
                'label_attr'=>['class'=>'text-bold my-2'],
                'invalid_message' => 'Veuillez vérifier vos mots de passe.',
                'options' => ['attr' => ['class' => 'password-field form-control mt-2']],
                'required' => true,
                'first_options'  => ['label' => 'Saisir le mot de passe une première fois',
                                    'attr'=>['class'=>'form-control mt-2']
                ],
                'second_options' => ['label' => 'Confirmez votre mot de passe',
                                    'label_attr'=>['class'=>'mt-2'],
                                    'attr'=>['class'=>'form-control mt-2']
                ],
            ])
            ->add('title', TextType::class, [
                'required'=>true,
                'label'=>"Civilité",
                'label_attr'=>['class'=>'text-bold my-2'],
                'attr'=>['class'=>'form-control mt-2']
            ])
            ->add('firstname', TextType::class, [
                'required'=>true,
                'label'=>"Prénom",
                'label_attr'=>['class'=>'text-bold my-2'],
                'attr'=>['class'=>'form-control mt-2']
            ])
            ->add('lastname', TextType::class, [
                'required'=>true,
                'label'=>"Nom",
                'label_attr'=>['class'=>'text-bold my-2'],
                'attr'=>['class'=>'form-control mt-2']
            ])
            ->add('email', EmailType::class, [
                'required'=>true,
                'label'=>"Adresse e-mail",
                'label_attr'=>['class'=>'text-bold my-2'],
                'attr'=>['class'=>'form-control mt-2']
            ])
            ->add('birthday', DateType::class, [
                'required'=>true,
                'label'=>"Date de naissance",
                'label_attr'=>['class'=>'text-bold my-2'],
                'input_format'=>'dd/mm/YYYY',
                'widget'=>'single_text',
                'attr'=>['class'=>'mt-2']
            ])
            ->add('save', SubmitType::class, options: [
                'label'=>"Ajouter",
                'attr'=>['class'=>'btn btn-add my-2']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Entity\Category;
use App\Entity\Invoice;
use App\Entity\Product;
use App\Entity\User;
use App\Form\UserType;
use App\Repository\AddressRepository;
use App\Repository\CategoryRepository;
use App\Repository\InvoiceRepository;
use App\Repository\ProductRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    private $productRepository;
    private $categoryRepository;
    private $addressRepository;

    public function __construct(ProductRepository $productRepository, CategoryRepository $categoryRepository, AddressRepository $addressRepository){
        $this->productRepository = $productRepository;
        $this->categoryRepository = $categoryRepository;
        $this->addressRepository = $addressRepository;
    }
    
    #[Route('/', name: 'default')]
    public function index(): Response
    {
        //retourne 4 produits flashs de facon aleatoire sur la page d'accueil
        $flashProducts = $this->productRepository->findBy(['isFlash' => true]);
        shuffle($flashProducts);

        $categories = $this->categoryRepository->findAll();
        
        
        return $this->render('default/index.html.twig', [
            'products' => array_splice($flashProducts, -4),
            'categories' => $categories,
            'controller_name' => 'DefaultController'
        ]);
    }

    #[Route('/product/{id}', name:'show_product', methods: ['GET'])]
    public function getOneProduct(Product $product){

        $categories = $this->categoryRepository->findAll();

        return $this->render('default/product.html.twig', ['product'=>$product , 'categories'=> $categories]);
    }

    #[Route('/category/{id}', name: 'show_category', methods: ['GET'])]
    public function show(Category $category): Response
    {
        $products = $this->productRepository->findAll();
        $categories = $this->categoryRepository->findAll();



        return $this->render('default/category-store.html.twig', [
            'category' => $category,
            'categories'=>$categories,
            'products' => $products,

        ]);
    }

    #[Route('/user/{id}', name: 'show_user', methods: ['GET'])]
    public function showUser(User $user): Response
    {

        //retourne 4 produits flashs de facon aleatoire sur la page d'accueil
        $flashProducts = $this->productRepository->findBy(['isFlash' => true]);
        shuffle($flashProducts);

        return $this->render('default/user/user-account.html.twig', [
            'user' => $user,
            'products' => array_splice($flashProducts, -4),
            'addresses'=> $this->addressRepository->findAll()
        ]);
    }

    #[Route('user/{id}/edit', name: 'edit_user', methods: ['GET', 'POST'])]
    public function editUser(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user);
            return $this->redirectToRoute('show_user', ['id'=>$user->getId()], Response::HTTP_SEE_OTHER);
        }

        //retourne 4 produits flashs de facon aleatoire sur la page d'accueil
        $flashProducts = $this->productRepository->findBy(['isFlash' => true]);
        shuffle($flashProducts);

        return $this->renderForm('default/user/user-edit.html.twig', [
            'user' => $user,
            'form' => $form,
            'products' => array_splice($flashProducts, -4),
        ]);
    }

    public function displayNav(){

        $categories = $this->categoryRepository->findAll();
        $sortedCategories=[];
        
        foreach($categories as $category){

            if($category->getParentCategory() !== null){
            $sortedCategories[$category->getParentCategory()->getName()][] = $category;
            }
        }
        return $this->render('default/parts/nav.html.twig', [
            'categories'=>$sortedCategories
        ]);
    }

}

templates/default/user/_delete_form-address.html.twig
<form method="post" action="{{ path('default_address_delete', {'id': address.id}) }}" onsubmit="return confirm('Voulez vous vraiment supprimer cette adresse?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ address.id) }}">
    <div class="row">
        <div class="col-2 text-end">
            <button class="btn btn-delete-small">x</button>
        </div>
        <div class="col-10 text-start">
            <p>Supprimer cette adresse</p>
        </div>
    </div>
</form>

templates/default/user/address-show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mettre à jour mes données{% endblock %}

{% block body %}
    {% include 'default/parts/header-account.html.twig' %}
    <main>
        <div class="container my-5 d-flex justify-content-center">

            <div class="row">

                <h1 class="h3 text-center">Voir le détail de vos addresses</h1>
                <div class="col-12">
                    <div class="card shadow-lg my-3 card-account">
                        <div class="row g-0">
                            <div class="col-lg-3">
                                <img src="{{ asset('img/logos/logoClear.jpg') }}" width="200px" class="img-fluid rounded p-2" alt="boutique" />
                            </div>
                            <div class="col-lg-9">
                                <div class="card-body">
                                    <h5 class="text-uppercase text-decoration-underline card-title text-end me-5">Mes adresses</h5>
                                    <p class="card-text">
                                        {% for address in app.user.addresses %}
                                    <div class="card-address my-3 p-1">
                                        {% if address.isDelivery == 1 and address.isBilling == 0 %}
                                            <p class="text-uppercase h6"><strong>Livraison</strong></p>
                                        {% elseif address.isBilling == 1 and address.isDelivery == 0 %}
                                            <p class="text-uppercase h6"><strong>Facturation</strong></p>
                                        {% else %}
                                            <p class="text-uppercase h6"><strong>Facturation & Livraison</strong></p>
                                        {% endif %}
                                        <p>{{ address.streetNumber }}, {{ address.street }}</p>
                                        <p class="text-uppercase">{{ address.zipcode }} {{ address.city }}</p>
                                        <div class=" card-footer text-end">
                                            <a href="{{ path('edit_address', {'id': address.id}) }}" class="text-white">Modifier</a>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 my-5">
                    <h4 class="text-center mt-5">Quelques produits qui pourraient vous plaire :</h4>
                    {% include 'default/parts/best-sellers.html.twig'%}
                </div>
            </div>

        </div>

    </main>

{% endblock %}

templates/default/user/show-order.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes commandes{% endblock %}

{% block body %}
    {% include 'default/parts/header-account.html.twig' %}
    <main>
        <div class="container my-5 d-flex justify-content-center">

            <div class="row">

                <h1 class="h3 text-center">Voir le détail de votre commande du {{ invoice.orderDate ? invoice.orderDate|date('d/m/Y') : '' }}</h1>
                <div class="col-12">
                    <div class="card shadow-lg my-3 card-account">
                        <div class="row g-0">
                            <div class="col-lg-3">
                                <img src="{{ asset('img/logos/logoClear.jpg') }}" width="200px" class="img-fluid rounded p-2" alt="boutique" />
                            </div>
                            <div class="col-lg-9">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-12">
                                            <h5 class="text-uppercase text-decoration-underline card-title text-end me-5 mb-5">Détail de la facture</h5>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-4 col-sm-6 col-xxs-12 me-1 mt-1">
                                            <div class="card card-account ms-3">
                                                <div class="card-header h6 text-center">
                                                    <strong>Adresse de facturation</strong>
                                                </div>
                                                <div class="card-body">
                                                    <p class="text-uppercase">{{ invoice.user.title }} {{ invoice.user.firstname }} {{ invoice.user.lastname }}</p>
                                                    {% for address in invoice.user.addresses%}
                                                        {% if address.isBilling == 1 %}
                                                            <p>{{ address.streetNumber }} {{ address.street }}</p>
                                                            <p class="text-uppercase">{{ address.zipCode }} {{ address.city }}</p>
                                                        {% endif %}
                                                    {% endfor %}
                                                </div>
                                                <div class="card-header h6 text-center">
                                                    <strong>Adresse de livraison</strong>
                                                </div>
                                                <div class="card-body">
                                                    <p class="text-uppercase">{{ invoice.user.title }} {{ invoice.user.firstname }} {{ invoice.user.lastname }}</p>
                                                    {% for address in invoice.user.addresses%}
                                                        {% if address.isDelivery == 1 %}
                                                            <p>{{ address.streetNumber }} {{ address.street }}</p>
                                                            <p class="text-uppercase">{{ address.zipCode }} {{ address.city }}</p>
                                                        {% endif %}
                                                    {% endfor %}
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-lg-6 col-sm-6 col-xxs-12 ms-1 mt-1">
                                            <div class="card card-account ms-3">
                                                <div class="card-header h6 text-center">
                                                    <strong>Informations sur la commande</strong>
                                                </div>
                                                <div class="card-body">
                                                    <p>Commande du: {{ invoice.orderDate ? invoice.orderDate|date('d/m/Y') : '' }}</p>
                                                    <p>Montant total de la commande: {{ invoice.TotalHTPrice }} €</p>
                                                    <p>Moyen de paiement: {{ invoice.paymentMethod }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div>
                            <div class="row card-body">
                                <div class="table-responsive-sm table-responsive-xxs">
                                    <table class="table table-sm text-white my-5 mx-5">
                                        <thead>
                                        <tr>
                                            <th></th>
                                            <th>Produit</th>
                                            <th>Quantité</th>
                                            <th>Prix total</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for productOrder in invoice.productOrders %}
                                            <tr>
                                                {% for picture in productOrder.product.pictures %}
                                                    {% if picture.isFront == 1 %}
                                                        <td><img src="{{asset('img/uploads/product/' ~ picture.href )}}" class="thumb-order p-1 border"></td>
                                                    {% endif %}
                                                {% endfor %}
                                                <td>{{ productOrder.product.title }}</td>
                                                <td>{{ productOrder.quantity }}</td>
                                                <td>{{ productOrder.TTCPrice|number_format(2,'.') }} €</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>Montant total de la facture</th>
                                            <td class="text-end"><strong>{{ invoice.TotalTTCPrice|number_format(2,'.') }} €</strong></td>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="card-body text-center">
                            <a href="{{ path('default_invoice_index') }}" class="text-white">Retour à mes commandes</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

templates/default/user/user-orders.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mettre à jour mes données{% endblock %}

{% block body %}
    {% include 'default/parts/header-account.html.twig' %}
    <main>
        <div class="container my-5 d-flex justify-content-center">

            <div class="row">

                <h1 class="h3 text-center">Vos commandes, {{app.user.title}} {{app.user.firstname}} {{app.user.lastname}}</h1>
                <div class="col-12">
                    <div class="card shadow-lg my-3 card-account">
                        <div class="row g-0">
                            <div class="col-lg-4">
                                <img src="{{ asset('img/smartRabbit.jfif') }}" class="img-fluid rounded-circle p-2" alt="boutique" />
                            </div>
                            <div class="col-lg-8">
                                <div class="card-body">
                                    <h5 class="text-uppercase text-decoration-underline card-title text-end me-5">Vos commandes</h5>
                                    <p class="card-body d-flex justify-content-center">
                                        {% for order in invoices %}
                                            {% if order.user.id == app.user.id %}
                                                <div class="row card-invoice my-3 p-1">
                                                    <div class="col-8">
                                                        <p>Date de la commande: {{ order.orderDate ? order.orderDate|date('d/m/Y') : '' }}</p>
                                                        <p>Montant total: {{ order.TotalTTCPrice|number_format(2,'.') }} €</p>
                                                        <p>Moyen de paiement: {{ order.paymentMethod }}</p>
                                                    </div>
                                                    <div class="col-4">
                                                        <a href="{{ path('default_invoice_show', {'id': order.id}) }}" class="text-white">Voir le détail de la commande</a>
                                                    </div>
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    </p>
                                </div>
                                <div class="card-body text-center">
                                    <a href="{{ path('show_user', {'id': app.user.id}) }}" class="text-white">Retour à l'espace client</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </main>

{% endblock %}